---
- name: Instalar actualizaciones
  yum:
    name: '*'
    state: latest
  register: update_output

- local_action:
    module: copy
    content: "{{ update_output.results }}"
    dest: "{{ tmp_dir }}/osUpdate"
  become: no

- name: Reiniciar VM
  command: /sbin/shutdown -r

- name: Esperar por VM detenida
  local_action:
    module: wait_for
    host: "{{ inventory_hostname }}"
    port: 22
    state: stopped
    timeout: 300
  become: no

- name: Esperar por VM encendida
  local_action:
    module: wait_for
    host: "{{ inventory_hostname }}"
    search_regex: OpenSSH
    port: 22
    timeout: 300
  become: no
