---
- name: Limpiar
  hosts: local
  gather_facts: false

  tasks:

  - find: path={{ tmp_dir }} file_type=file
    register: tmp_files

  - name: Eliminar archivos temporales
    file: state=absent path={{ item.path }}
    with_items:
      - "{{ tmp_files.files }}"
