
# 08/2018  arenaud.
---
- name: Login to vcloud api
  hosts: localhost
  gather_facts: false
  environment: "{{ proxy_env }}"
  tasks:

  - name: Codificar credenciales
    shell: echo -n '{{ api_user }}@{{ org_name }}:{{ api_password }}' | base64
    register: encodedCreds
  
  - debug: var=encodedCreds

  - shell: echo $dude $no_proxy $http_proxy $https_proxy
    delegate_to: localhost

  - name: Autenticación vCloud
    
    proxy_env:
      http_proxy: "http://proxy.wido.com.uy:3128"
      https_proxy: "http://proxy.wido.com.uy:3128"
    #environment: "{{proxy_env}}"
    uri:
      url: "{{ api_host }}/api/sessions"
      headers:
        Accept: "application/*+xml;version=1.5"
        Authorization: "Basic {{ encodedCreds.stdout }}"
      method: POST
      return_content: yes
      follow_redirects: all 
      dest: "{{ tmp_dir }}/login.xml"
      validate_certs: no 
    register: login
  
  - debug: var=login
 


