---
- name: Instalar última versión de OSSEC
  yum:
    name: "{{ item }}"
    state: latest
  register: install_output
  with_items:
    - ossec-hids
    - ossec-hids-agent

- local_action:
    module: copy
    content: "{{ item.results }}"
    dest: "{{ tmp_dir }}/ossecInstall"
  become: no
  with_items: "{{ install_output.results }}"

- name: Servicio de OSSEC disabled y unmasked
  systemd: name=ossec-hids enabled=no masked=no

