---
- name: Remuevo el servicio Zabbix
  win_service:
    name: Zabbix Agent
    state: absent

- name: Remuevo archivos residuales
  win_file:
    path: C:\Zabbix
    state: absent

- name: Descargando Zabbix
  win_get_url:
    url: https://www.zabbix.com/downloads/3.4.6/zabbix_agents_3.4.6.win.zip
    dest: C:\zabbix.zip

- name: Descomprimiendo Zabbix
  win_unzip:
    src: C:\zabbix.zip
    dest: C:\Zabbix
    creates: C:\Zabbix

- name: Borrando zip de Zabbix
  win_file:
    path: C:\Zabbix.zip
    state: absent

- name: Instalando Zabbix
  win_shell: C:\Zabbix\bin\win64\zabbix_agentd.exe --config C:\Zabbix\conf\zabbix_agentd.win.conf --install