---
- name: Instalar última versión de filebeat
  yum:
    name: filebeat
    state: latest
  register: install_output

- local_action:
    module: copy
    content: "{{ install_output.results }}"
    dest: "{{ tmp_dir }}/filebeatInstall"
  become: no

- name: Servicio de filebeat disabled y unmasked
  systemd: name=filebeat enabled=no masked=no

