server.host: "0.0.0.0"
server.name: "syslog.wido.uy"
server.basePath: "/wido" 
#"NODE_OPTIONS=--max-old-space-size=800"
elasticsearch.url: "http://elasticsearch-coordinator:9200"
kibana.index: ".kibana"
regionmap:
  includeElasticMapsService: false
  layers:
   - name: "Departmentos de Uruguay"
     url: "https://data.wido.uy/syslog/Uruguay_v2.GeoJson"
     attribution: "OpenMaps.layer"
     fields:
      - name: "name"
        description: "Departamentos"
      - name: "wikipedia"
        description: "Region"
