---
- name: Encender/Detener vApp
  hosts: localhost
  gather_facts: false
  environment: "{{ proxy_env }}" 
  tasks:

  - name: Codificar credenciales
    shell: echo -n '{{ api_user }}@{{ org_name }}:{{ api_password }}' | base64
    register: encodedCreds

  - name: Autenticación vCloud
    environment: "{{ proxy_env }}" 
    uri:
      url: "{{ api_host }}/api/sessions"
      headers:
        Accept: "application/*+xml;version=1.5"
        Authorization: "Basic {{ encodedCreds.stdout }}"
      method: POST
      dest: "{{ tmp_dir }}/login.xml"
      validate_certs: False
    register: login

  - name: Extraer href Organización
    xml_read:
      xmlfile: "{{ tmp_dir }}/login.xml"
      xpath: "/n:Session/n:Link[@name='{{ org_name }}']/@href"
      namespaces: "n=http://www.vmware.com/vcloud/v1.5"
    register: org_href

  - name: Obtener contenido Organización
    uri:
      url: "{{ org_href.value }}"
      headers:
        Accept: "application/*+xml;version=1.5"
        Cookie: "{{ login.set_cookie }}"
      method: GET
      dest: "{{ tmp_dir }}/org.xml"
      validate_certs: False

  - name: Extraer href vDC
    xml_read:
      xmlfile: "{{ tmp_dir }}/org.xml"
      xpath: "/n:Org/n:Link[@name='{{ vdc_name }}']/@href"
      namespaces: "n=http://www.vmware.com/vcloud/v1.5"
    register: vdc_href

  - name: Obtener contenido vDC
    uri:
      url: "{{ vdc_href.value }}"
      headers:
        Accept: "application/*+xml;version=1.5"
        Cookie: "{{ login.set_cookie }}"
      method: GET
      dest: "{{ tmp_dir }}/vdc.xml"
      validate_certs: False

  - name: Extraer href vApp
    xml_read:
      xmlfile: "{{ tmp_dir }}/vdc.xml"
      xpath: "/n:Vdc/n:ResourceEntities/n:ResourceEntity[@name='{{ vapp_name }}']/@href"
      namespaces: "n=http://www.vmware.com/vcloud/v1.5"
    register: vapp_href

  - set_fact: vapp_state="noDetenida"

  - name: Verificar vApp NO detenida
    uri:
      url: "{{ vapp_href.value }}"
      headers:
        Accept: "application/*+xml;version=1.5"
        Cookie: "{{ login.set_cookie }}"
      method: GET
      dest: "{{ tmp_dir }}/vapp.xml"
      return_content: yes
      validate_certs: False
    register: check_response

  - set_fact: vapp_state="detenida"
    when: check_response.content | search('status="8"')

  - name: Detener vApp
    uri:
      url: "{{ vapp_href.value }}/action/undeploy"
      body: "{{ lookup('file', 'templates/UndeployVAppParams.xml') }}"
      headers:
        Accept: "application/*+xml;version=1.5"
        Cookie: "{{ login.set_cookie }}"
        Content-Type: application/vnd.vmware.vcloud.undeployVAppParams+xml
      method: POST
      status_code: 202
      validate_certs: False
    register: response
    when: vapp_state == "noDetenida"

  - name: Verificar vApp detenida
    uri:
      url: "{{ vapp_href.value }}"
      headers:
        Accept: "application/*+xml;version=1.5"
        Cookie: "{{ login.set_cookie }}"
      method: GET
      dest: "{{ tmp_dir }}/vapp.xml"
      return_content: yes
      validate_certs: False
    register: verif_response
    until: verif_response.content | search('status="8"')
    retries: 60
    delay: 2
    when: vapp_state == "noDetenida"
