---
- name: Instalar última versión de zabbix-agent
  yum:
    name: zabbix-agent
#    disablerepo: '*'
#    enablerepo: local
#    disablerepo: local
    state: latest
  register: install_output

- local_action:
    module: copy
    content: "{{ install_output.results }}"
    dest: "{{ tmp_dir }}/zbxInstall"
  become: no

- name: Iniciar servicio de zabbix
  systemd: state=started name=zabbix-agent
